# Generated by Django 5.0.6 on 2024-07-04 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasupati', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
