# Generated by Django 4.2.14 on 2024-07-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pasupati", "0002_fruit_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="name",
            field=models.CharField(default="User", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="phone",
            field=models.IntegerField(default=0),
        ),
    ]
